# -*- coding: utf-8 -*-
"""paper1cv1_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SC1tko3CUAWu5zb4prkLiAmOjF5gDiVq
"""

# Import libraries
import os
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from google.colab import drive
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, f1_score
from sklearn.utils.class_weight import compute_class_weight

# -------------------------------------------------------
# 0. KONFIGURASI GLOBAL
# -------------------------------------------------------

print("GPU Available:", tf.config.list_physical_devices('GPU'))
print("TensorFlow version:", tf.__version__)

drive.mount('/content/drive')

base_path = '/content/drive/MyDrive/Paper1bv1'
source_path = f'{base_path}/datasets/new_pv_augmented'  # Dataset dengan augmentasi presisi
local_dataset_path = '/content/new_pv_augmented_local'

dataset_path = local_dataset_path
print(f"Dataset path updated to: {dataset_path}")

IMG_HEIGHT, IMG_WIDTH = 224, 224
BATCH_SIZE = 32
TEST_SPLIT = 0.25

import os

print(f"Cleaning hidden files from: {dataset_path}")

removed_count = 0
for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.startswith('._'):
            file_path = os.path.join(root, file)
            try:
                os.remove(file_path)
                # print(f"Removed: {file_path}")
                removed_count += 1
            except OSError as e:
                print(f"Error removing {file_path}: {e}")

print(f"Finished cleaning. Total hidden files removed: {removed_count}")

# -------------------------------------------------------
# 1. DEFINISI SKENARIO (S0–S6)
# -------------------------------------------------------

SEED = 189 # 21 189 1337

"""
S0: Baseline full
    - Loss: CCE
    - Weight: No
    - Head: baseline
S1: Effect of class weight
    - Loss: CCE
    - Weight: Yes
    - Head: baseline
S2: Effect of deeper head
    - Loss: CCE
    - Weight: Yes
    - Head: deeper
S3: Effect of loss design (focal)
    - Loss: Focal
    - Weight: Yes
    - Head: baseline
S4: Lighter head
    - Loss: CCE
    - Weight: Yes
    - Head: lighter
S5: Best combo (contoh: focal + deeper)
    - Loss: Focal
    - Weight: Yes
    - Head: deeper
S6: Baseline focal loss
    - Loss: Focal
    - Weight: No
    - Head: baseline

"""

SCENARIO = "S6"  # ganti ke: "S0","S1","S2","S3","S4","S5", "S6"

SCENARIO_CONFIG = {
    "S0": {"LOSS_VARIANT": "cce",   "USE_CLASS_WEIGHT": False, "HEAD_VARIANT": "baseline"},
    "S1": {"LOSS_VARIANT": "cce",   "USE_CLASS_WEIGHT": True,  "HEAD_VARIANT": "baseline"},
    "S2": {"LOSS_VARIANT": "cce",   "USE_CLASS_WEIGHT": True,  "HEAD_VARIANT": "deeper"},
    "S3": {"LOSS_VARIANT": "focal", "USE_CLASS_WEIGHT": True,  "HEAD_VARIANT": "baseline"},
    "S4": {"LOSS_VARIANT": "cce",   "USE_CLASS_WEIGHT": True,  "HEAD_VARIANT": "lighter"},
    "S5": {"LOSS_VARIANT": "focal", "USE_CLASS_WEIGHT": True,  "HEAD_VARIANT": "deeper"},
    "S6": {"LOSS_VARIANT": "focal", "USE_CLASS_WEIGHT": False,  "HEAD_VARIANT": "baseline"},
}

config = SCENARIO_CONFIG[SCENARIO]
LOSS_VARIANT = config["LOSS_VARIANT"]
USE_CLASS_WEIGHT = config["USE_CLASS_WEIGHT"]
HEAD_VARIANT = config["HEAD_VARIANT"]

print(f"\n=== Running Scenario {SCENARIO} ===")
print(f"LOSS_VARIANT    : {LOSS_VARIANT}")
print(f"USE_CLASS_WEIGHT: {USE_CLASS_WEIGHT}")
print(f"HEAD_VARIANT    : {HEAD_VARIANT}")
print(f"SEED            : {SEED}")

# -------------------------------------------------------
# 2. OBSERVASI DATASET
# -------------------------------------------------------

IMG_HEIGHT, IMG_WIDTH = 224, 224
BATCH_SIZE = 32
# TEST_SPLIT = 0.25

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# ImageDataGenerator untuk data pelatihan (hanya rescale, karena augmentasi sudah ada di dataset)
train_datagen = ImageDataGenerator(
    rescale=1./255
    # Tidak perlu augmentasi data di sini jika dataset sudah diaugmentasi
    # Tidak perlu validation_split
)

# ImageDataGenerator untuk data validasi (hanya rescale)
validation_datagen = ImageDataGenerator(
    rescale=1./255,
    # validation_split=TEST_SPLIT
    # Tidak perlu augmentasi data untuk validasi
)

# ImageDataGenerator untuk data validasi (hanya rescale)
test_datagen = ImageDataGenerator(
    rescale=1./255,
    # validation_split=TEST_SPLIT
    # Tidak perlu augmentasi data untuk validasi
)

def list_subfolders_and_file_counts(root_dir):
    print(f"\n📁 Direktori utama: {root_dir}\n")
    for subfolder in os.listdir(root_dir):
        subfolder_path = os.path.join(root_dir, subfolder)
        if os.path.isdir(subfolder_path):
            file_count = sum(
                1 for item in os.listdir(subfolder_path)
                if os.path.isfile(os.path.join(subfolder_path, item))
            )
            print(f"📂 Subfolder: {subfolder} \u2192 {file_count} file(s)")

train_path = f'{dataset_path}/train'
classes = os.listdir(train_path)
print(f"\nTrain folder: {len(classes)}")

total_images = sum(
    len(os.listdir(os.path.join(train_path, c)))
    for c in classes if os.path.isdir(os.path.join(train_path, c))
)
print(f"Total train images: {total_images}")

print("\nTrain images:")
list_subfolders_and_file_counts(f'{dataset_path}/train')

print("\nValid images:")
list_subfolders_and_file_counts(f'{dataset_path}/valid')

print("\nTest images:")
list_subfolders_and_file_counts(f'{dataset_path}/test')

# Distribusi kelas train
color_path = f'{dataset_path}/train'
subfolders = [f for f in os.listdir(color_path) if os.path.isdir(os.path.join(color_path, f))]
image_counts = {}
for subfolder in subfolders:
    subfolder_path = os.path.join(color_path, subfolder)
    file_count = sum(
        1 for item in os.listdir(subfolder_path)
        if os.path.isfile(os.path.join(subfolder_path, item))
    )
    image_counts[subfolder] = file_count

total_color_images = sum(image_counts.values())
print(f"\nTotal images in train directory: {total_color_images}")

image_counts_series = pd.Series(image_counts).sort_values(ascending=False)

# Get class names from the series index
class_names_in_order = image_counts_series.index.tolist()

# Generator untuk data pelatihan, mengarah ke folder train
train_generator = train_datagen.flow_from_directory(
    f'{dataset_path}/train', # Path ke folder train Anda
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    seed=SEED,
    shuffle=True  # Training harus di-shuffle
)

# Get the mapping from class names to integer codes (assuming train_generator is available from a previous cell)
# This assumes train_generator has been created and is accessible.
class_to_idx = train_generator.class_indices

# Create a list of combined labels with 'C' + code format
combined_labels = [f"C{class_to_idx[name]}" for name in class_names_in_order]

plt.figure(figsize=(15, 7))
image_counts_series.plot(kind='bar')
plt.title('Number of Images per Class in Train Dataset')
plt.xlabel('Class Code') # Changed label for clarity
plt.ylabel('Number of Images')
plt.xticks(ticks=range(len(combined_labels)), labels=combined_labels, rotation=90) # Modified line
plt.tight_layout()
plt.show()

# -------------------------------------------------------
# 3. DATA GENERATOR
# -------------------------------------------------------

validation_generator = validation_datagen.flow_from_directory(
    f'{dataset_path}/valid',
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    seed=SEED,
    shuffle=True
)

test_generator = test_datagen.flow_from_directory(
    f'{dataset_path}/test',
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    seed=SEED,
    shuffle=False
)

print(f"\nFound {train_generator.n} images / {train_generator.num_classes} classes for training.")
print(f"Found {validation_generator.n} images / {validation_generator.num_classes} classes for validation.")
print(f"Found {test_generator.n} images / {test_generator.num_classes} classes for testing.")

# -------------------------------------------------------
# 4. CLASS WEIGHT (untuk skenario dengan pembobotan)
# -------------------------------------------------------

class_weight_dict = None
if USE_CLASS_WEIGHT:
    print("\nComputing class weights to handle imbalance...")
    class_labels_arr = np.unique(train_generator.classes)
    class_weights = compute_class_weight(
        class_weight='balanced',
        classes=class_labels_arr,
        y=train_generator.classes
    )
    class_weight_dict = dict(enumerate(class_weights))
    print("Class weights computed:")
    for class_id, weight in class_weight_dict.items():
        class_name = list(train_generator.class_indices.keys())[class_id]
        print(f"  {class_name}: {weight:.4f}")
else:
    print("\nClass weights: NOT used in this scenario.")

# -------------------------------------------------------
# 5. LOSS FUNCTION (CCE, label smoothing, focal)
# -------------------------------------------------------

from tensorflow.keras import backend as K

def focal_loss(gamma=2., alpha=0.25):
    def focal(y_true, y_pred):
        y_pred = K.clip(y_pred, K.epsilon(), 1. - K.epsilon())
        cross_entropy = -y_true * K.log(y_pred)
        weight = alpha * K.pow(1 - y_pred, gamma)
        loss = weight * cross_entropy
        return K.sum(loss, axis=1)
    return focal

def get_loss():
    if LOSS_VARIANT == "cce":
        return "categorical_crossentropy"
    elif LOSS_VARIANT == "label_smoothing":
        return tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1)
    elif LOSS_VARIANT == "focal":
        return focal_loss(gamma=2., alpha=0.25)
    else:
        return "categorical_crossentropy"

loss_fn = get_loss()
print(f"\nUsing loss function variant: {LOSS_VARIANT}")

# -------------------------------------------------------
# 6. CLASSIFIER HEAD VARIANT
# -------------------------------------------------------

def create_mobilenetv3_small():
    base_model = tf.keras.applications.MobileNetV3Small(
        weights='imagenet',
        include_top=False,
        input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)
    )
    base_model.trainable = False

    x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)

    if HEAD_VARIANT == "baseline":
        x = tf.keras.layers.Dense(256, activation='relu')(x)
        x = tf.keras.layers.Dropout(0.5)(x)

    elif HEAD_VARIANT == "deeper":
        x = tf.keras.layers.Dense(512, activation='relu')(x)
        x = tf.keras.layers.Dropout(0.5)(x)
        x = tf.keras.layers.Dense(256, activation='relu')(x)
        x = tf.keras.layers.Dropout(0.5)(x)

    elif HEAD_VARIANT == "lighter":
        x = tf.keras.layers.Dense(128, activation='relu')(x)
        # dropout opsional, bisa ditambahkan jika ingin
        # x = tf.keras.layers.Dropout(0.3)(x)

    outputs = tf.keras.layers.Dense(train_generator.num_classes, activation='softmax')(x)
    model = tf.keras.Model(inputs=base_model.input, outputs=outputs)
    return model

mobilenet_model = create_mobilenetv3_small()

mobilenet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=loss_fn,
    metrics=['accuracy', tf.keras.metrics.top_k_categorical_accuracy]
)

mobilenet_model.summary()

# -------------------------------------------------------
# 7. CALLBACKS
# -------------------------------------------------------

print(SEED)
if SEED != 1337:
  model_tag = f"mobilenetv3_{SCENARIO}_{SEED}"
else:
  model_tag = f"mobilenetv3_{SCENARIO}"

model_save_path = f'{base_path}/models/{model_tag}_best.keras'
print(model_save_path)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=3, verbose=1),
    tf.keras.callbacks.ModelCheckpoint(
        model_save_path,
        save_best_only=True,
        monitor='val_accuracy',
        verbose=1
    )
]

fit_kwargs = {}
if USE_CLASS_WEIGHT and class_weight_dict is not None:
    fit_kwargs['class_weight'] = class_weight_dict

# -------------------------------------------------------
# 8. STAGE 1: INITIAL TRAINING
# -------------------------------------------------------

print(f"\n========== STAGE 1: Initial Training ({SCENARIO}) ==========")

initial_history = mobilenet_model.fit(
    train_generator,
    epochs=5,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1,
    **fit_kwargs
)

history_dir = f'{base_path}/results'
os.makedirs(history_dir, exist_ok=True)

with open(f'{history_dir}/{model_tag}_initial_history.pkl', 'wb') as f:
    pickle.dump(initial_history.history, f)

# -------------------------------------------------------
# 9. STAGE 2: FINE-TUNING
# -------------------------------------------------------

print(f"\n========== STAGE 2: Fine-Tuning ({SCENARIO}) ==========")

fine_tune_model = tf.keras.models.load_model(model_save_path, custom_objects={'focal': focal_loss()})
print(f"Loaded best model from {model_save_path}")

# --- BEGIN FIX ---
# The actual base model (MobileNetV3Small) seems to be unpacked into fine_tune_model.layers.
# This means fine_tune_model.layers[2] is a Conv2D layer, not the MobileNetV3Small model object itself.
# We need to iterate over fine_tune_model.layers directly and identify the backbone layers.

# First, set all layers in the entire model to be trainable (as we want to fine-tune).
# We will then selectively freeze early layers of the backbone.
for layer in fine_tune_model.layers:
    layer.trainable = True

# Identify the approximate start and end of the MobileNetV3Small backbone layers.
# Assuming InputLayer (0) and Rescaling (1) are at the beginning.
# And the custom classification head layers are at the end.

start_backbone_index = 2 # Usually after InputLayer and potential Rescaling layer.

# Count the number of layers in the custom head based on HEAD_VARIANT
num_head_layers = 0
if HEAD_VARIANT == "baseline":
    # GlobalAveragePooling2D, Dense(256), Dropout, Dense(38) = 4 layers
    num_head_layers = 4
elif HEAD_VARIANT == "deeper":
    # GlobalAveragePooling2D, Dense(512), Dropout, Dense(256), Dropout, Dense(38) = 6 layers
    num_head_layers = 6
elif HEAD_VARIANT == "lighter":
    # GlobalAveragePooling2D, Dense(128), Dense(38) = 3 layers
    num_head_layers = 3

# Calculate the effective end index of the backbone layers (before the custom head)
end_backbone_index = len(fine_tune_model.layers) - num_head_layers

# Now, freeze the early layers of the backbone.
# `unfreeze_from_layer` is still applied relative to the end of the *backbone*.
# Convert it to an absolute index within the backbone slice.

unfreeze_from_layer = -20 # User's desired number of layers to unfreeze from the end of backbone

# Calculate the index within fine_tune_model.layers from which to start unfreezing
# (i.e., layers before this index in the backbone will be frozen).
# This accounts for the start of the backbone layers (start_backbone_index)
# and the layers that should remain frozen at the beginning of the backbone.
freeze_until_index = end_backbone_index + unfreeze_from_layer # This is the index (exclusive) until which layers are frozen

# Ensure `freeze_until_index` is not less than `start_backbone_index`.
freeze_until_index = max(start_backbone_index, freeze_until_index)

print(f"Freezing layers from index {start_backbone_index} up to {freeze_until_index-1} (inclusive) of the backbone.")
print(f"Unfreezing layers from index {freeze_until_index} up to {end_backbone_index-1} (inclusive) of the backbone, and all head layers.")

for i in range(start_backbone_index, freeze_until_index):
    layer = fine_tune_model.layers[i]
    if not isinstance(layer, tf.keras.layers.BatchNormalization): # Keep BatchNormalization layers frozen (good practice for fine-tuning)
        layer.trainable = False

print(f"Total layers in fine_tune_model: {len(fine_tune_model.layers)}")
# --- END FIX ---

fine_tune_learning_rate = 1e-5
fine_tune_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=fine_tune_learning_rate),
    loss=loss_fn,
    metrics=['accuracy', tf.keras.metrics.top_k_categorical_accuracy]
)

fine_tune_model.summary()

finetune_history = fine_tune_model.fit(
    train_generator,
    epochs=30,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1,
    **fit_kwargs
)

with open(f'{history_dir}/{model_tag}_finetune_history.pkl', 'wb') as f:
    pickle.dump(finetune_history.history, f)

# -------------------------------------------------------
# 10. EVALUASI pada VALIDATION & TEST (tanpa threshold tuning detail di sini)
# -------------------------------------------------------

best_model = tf.keras.models.load_model(model_save_path, custom_objects={'focal': focal_loss()})
val_loss, val_accuracy, val_top5 = best_model.evaluate(validation_generator)
print(f"\nValidation - Loss: {val_loss:.4f} | Acc: {val_accuracy:.4f} | Top-5: {val_top5:.4f}")

# Prediksi pada test standar (argmax)
y_pred = best_model.predict(test_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = test_generator.classes
class_labels = list(test_generator.class_indices.keys())

# 1) Evaluasi standar (tanpa threshold tuning)
cm = confusion_matrix(y_true, y_pred_classes)
print("\nConfusion Matrix:\n", cm)


# Simpan y_pred, y_pred_classes and y_true
pred_dict = {
    "y_pred": y_pred,
    "y_pred_classes": y_pred_classes,
    "y_true": y_true,
    "filepaths": test_generator.filepaths,  # berguna untuk analisis error
    "class_indices": test_generator.class_indices
}
with open(f"{history_dir}/{model_tag}_predictions.pkl", "wb") as f:
    pickle.dump(pred_dict, f)

# Simpan CM
np.savetxt(f"{history_dir}/{model_tag}_confusion_matrix_argmax.csv", cm, delimiter=",")

# Classification report
report = classification_report(y_true, y_pred_classes, target_names=class_labels, digits=4, output_dict=True)
df_report = pd.DataFrame(report).transpose()
print(df_report)
df_report.to_csv(f"{history_dir}/{model_tag}_classification_report_argmax.csv")

# Plot CM
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
fig, ax = plt.subplots(figsize=(15, 15))
disp.plot(ax=ax, cmap="Blues", xticks_rotation=90)
plt.title(f"Confusion Matrix ({SCENARIO})")
plt.tight_layout()
plt.show()

'''
# Threshold Tuning -- Leave this commented out for now
# 2) Threshold tuning sederhana (pakai threshold tetap per kelas)
probs = y_pred  # (n_samples, n_classes)

n_classes = probs.shape[1]
thresholds = np.array([0.5] * n_classes)

minor_class_names = [
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
    'Corn_(maize)___Northern_Leaf_Blight',
    'Potato___healthy',
    'Tomato___Early_blight',
    'Tomato___Late_blight',
    'Tomato___Septoria_leaf_spot',
    'Tomato___Spider_mites Two-spotted_spider_mite',
    'Tomato___Target_Spot'
]
minor_class_indices = [class_labels.index(cls) for cls in minor_class_names]
for idx in minor_class_indices:
    thresholds[idx] = 0.4  # contoh nilai tetap

y_pred_threshold = []
for i in range(probs.shape[0]):
    class_idx = np.argmax(probs[i])
    if probs[i, class_idx] >= thresholds[class_idx]:
        y_pred_threshold.append(class_idx)
    else:
        eligible = np.where(probs[i] >= thresholds)[0]
        if len(eligible) > 0:
            y_pred_threshold.append(eligible[np.argmax(probs[i, eligible])])
        else:
            y_pred_threshold.append(class_idx)

y_pred_threshold = np.array(y_pred_threshold)

print("\nClassification Report (Custom Threshold 0.3 minor):")
report_thresh = classification_report(
    y_true, y_pred_threshold, target_names=class_labels, digits=4, output_dict=True
)
df_report_thresh = pd.DataFrame(report_thresh).transpose()
print(df_report_thresh)

df_report_thresh.to_csv(f"{history_dir}/{model_tag}_classification_report_threshold_fixed.csv")
# End of Threshold Tuning
'''

print(f"\n=== Selesai skenario {SCENARIO} ===")

import pandas as pd

history_dir = f'{base_path}/results'

data = pd.read_pickle(f"{history_dir}/{model_tag}_initial_history.pkl")
df = pd.DataFrame(data)
df.to_csv(f"{history_dir}/{model_tag}_initial_history.csv", index=False)
print("Konversi selesai. File CSV siap di-upload.")

data = pd.read_pickle(f"{history_dir}/{model_tag}_finetune_history.pkl")
df = pd.DataFrame(data)
df.to_csv(f"{history_dir}/{model_tag}_finetune_history.csv", index=False)
print("Konversi selesai. File CSV siap di-upload.")

import pandas as pd

#base_path = '/content/drive/MyDrive/Paper1bv1'
#history_dir = f'{base_path}/models'

# Assuming model_tag is defined in a previous cell, as per notebook context.
# For example, from cell r_zAoI9sftNP, model_tag is f"mobilenetv3_{SCENARIO}"
# and SCENARIO is "S6" from cell 7d_QAFPV3djo, making model_tag = "mobilenetv3_S6"
# model_tag = f"mobilenetv3_{SCENARIO}" # Re-defining model_tag for clarity/standalone execution

# Load the dictionary containing predictions. Using the correct model_tag.
predictions_data = pd.read_pickle(f"{history_dir}/{model_tag}_predictions.pkl")

# The original error occurred because 'y_pred' is a 2D array.
# We need to explicitly handle it by creating a DataFrame from 1D data first,
# and then adding the probabilities from the 2D 'y_pred' array as separate columns.

# Create the main DataFrame with 1D data points
df_results = pd.DataFrame({
    'y_true': predictions_data['y_true'],
    'y_pred_classes': predictions_data['y_pred_classes'],
    'filepaths': predictions_data['filepaths']
})

# Extract the probabilities array
y_pred_probabilities = predictions_data['y_pred']

# Get class names from the stored class_indices to name the probability columns
class_indices = predictions_data['class_indices']
# Create a mapping from integer index to class name
idx_to_class = {v: k for k, v in class_indices.items()}

# Generate column names for the probabilities (e.g., 'prob_Apple___Apple_scab')
num_classes = y_pred_probabilities.shape[1]
prob_col_names = [f'prob_{idx_to_class.get(i, f"unknown_class_{i}")}' for i in range(num_classes)]

# Create a DataFrame from the probabilities array with appropriate column names
df_probabilities = pd.DataFrame(y_pred_probabilities, columns=prob_col_names)

# Concatenate the two DataFrames horizontally
df_final = pd.concat([df_results, df_probabilities], axis=1)

# Save the final DataFrame to a CSV file. Using the correct model_tag.
df_final.to_csv(f"{history_dir}/{model_tag}_predictions.csv", index=False)
print("Konversi selesai. File CSV siap di-upload.")